### PR TITLE
callpackage

### PR DESCRIPTION
**Pull request by viperML**
As we are not using a function for the package definition, I don't know how `makeOverridable` / `override` would fit in

### CODE REVIEW

**Review by NotAShelf — APPROVED** [review]
what

**Comment by nrabulinski** [comment]
Very cool, very based

For overriding you could potentially do something like 

```nix
callPackageScopedWith = autoArgs: f: let
  res = builtins.scopedImport autoArgs f;
  override = newArgs: callPackageScopedWith (autoArgs // newArgs) f;
in if builtins.isAttrs res then (res // { inherit override; }) else res;
```

Typed on my phone off the top of my head so may not work out of the box but you get the idea

**Comment by viperML** [comment]
What was the reasoning behind `if builtins.isAttrs res then ... else res` ?

**Comment by nrabulinski** [comment]
> What was the reasoning behind `if builtins.isAttrs res then ... else res` ?

Just a safety measure if the resulting value wasn't an attrset so you still get that value returned instead of erroring at `//`

**Pull request merged**
